import { useMemo, useState } from 'react';
import { ChevronDown, ChevronRight, FileCode2, FileJson2, FilePlus2, FileText, Folder, FolderOpen, LoaderCircle, Trash2 } from 'lucide-react';

const fileIcon = (path) => path.endsWith('.json') ? FileJson2 : path.endsWith('.jsx') || path.endsWith('.js') ? FileCode2 : FileText;
const indentClass = (depth) => ['pl-2', 'pl-5', 'pl-8', 'pl-11', 'pl-14'][Math.min(depth, 4)];
function buildTree(files) { const root = {}; files.forEach((file) => { const parts = file.path.split('/'); let current = root; parts.forEach((part, index) => { if (index === parts.length - 1) current[part] = file; else current[part] ||= {}; current = index === parts.length - 1 ? current : current[part]; }); }); return root; }
function Tree({ node, selectedFile, onSelect, onDelete, depth = 0 }) { return Object.entries(node).sort(([a, valueA], [b, valueB]) => (typeof valueA === 'object' && !valueA.id ? -1 : 1) - (typeof valueB === 'object' && !valueB.id ? -1 : 1) || a.localeCompare(b)).map(([name, value]) => typeof value === 'object' && !value.id ? <FolderNode key={name} name={name} node={value} selectedFile={selectedFile} onSelect={onSelect} onDelete={onDelete} depth={depth} /> : <FileNode key={value.id} file={value} selected={selectedFile?.id === value.id} onSelect={onSelect} onDelete={onDelete} depth={depth} />); }
function FolderNode({ name, node, selectedFile, onSelect, onDelete, depth }) { const [open, setOpen] = useState(true); return <div><button onClick={() => setOpen(!open)} className={`focus-ring flex w-full items-center gap-1.5 rounded-lg py-1.5 text-left text-xs font-medium text-slate-400 hover:bg-white/5 hover:text-slate-200 ${indentClass(depth)}`}>{open ? <ChevronDown size={14} /> : <ChevronRight size={14} />}{open ? <FolderOpen size={15} className="text-violet-300/80" /> : <Folder size={15} className="text-violet-300/80" />}<span className="truncate">{name}</span></button>{open && <Tree node={node} selectedFile={selectedFile} onSelect={onSelect} onDelete={onDelete} depth={depth + 1} />}</div>; }
function FileNode({ file, selected, onSelect, onDelete, depth }) { const Icon = fileIcon(file.path); return <div className={`group flex items-center rounded-lg transition ${selected ? 'bg-violet-400/15 text-violet-100 shadow-inner shadow-violet-500/10' : 'text-slate-500 hover:bg-white/5 hover:text-slate-200'}`}><button onClick={() => onSelect(file.id)} className={`focus-ring flex min-w-0 flex-1 items-center gap-2 py-1.5 text-left text-xs ${indentClass(depth)}`}><Icon size={14} className={selected ? 'text-violet-300' : 'text-slate-600'} /><span className="truncate">{file.path.split('/').at(-1)}</span></button><button onClick={() => onDelete(file)} aria-label={`Delete ${file.path}`} className="mr-1 hidden rounded p-1 text-slate-600 hover:bg-rose-500/10 hover:text-rose-300 group-hover:block"><Trash2 size={13} /></button></div>; }
export default function FileExplorer({ files, selectedFile, loading, error, onSelect, onNew, onDelete, onInitialize }) { const tree = useMemo(() => buildTree(files), [files]); return <aside className="flex min-h-0 flex-col border-r border-white/10 bg-[#0a0e16]"><div className="border-b border-white/10 px-3 py-3"><div className="flex items-center justify-between"><div><p className="section-label">Workspace</p><p className="mt-1 text-xs font-medium text-slate-300">Project Files</p></div><button onClick={onNew} aria-label="New file" className="focus-ring rounded-lg p-1.5 text-violet-300 hover:bg-violet-400/10"><FilePlus2 size={16} /></button></div></div><div className="min-h-0 flex-1 overflow-y-auto p-2">{loading ? <div className="grid h-full place-items-center"><LoaderCircle className="animate-spin text-violet-400" size={18} /></div> : error ? <p className="p-2 text-sm text-rose-300">{error}</p> : files.length ? <Tree node={tree} selectedFile={selectedFile} onSelect={onSelect} onDelete={onDelete} /> : <div className="p-3 text-sm text-slate-400"><p>No files yet.</p><button onClick={onInitialize} className="mt-3 text-xs text-violet-300 hover:text-violet-200">Initialize starter files</button></div>}</div></aside>; }
