import { useState } from 'react';
import { AlertCircle, CheckCircle, Download, ExternalLink, Globe2, Loader, Rocket, Trash2 } from 'lucide-react';

const providers = { VERCEL: 'Vercel', NETLIFY: 'Netlify', OTHER: 'CraftAI' };
const statusStyles = { PENDING: 'border-amber-300/20 bg-amber-300/10 text-amber-200', BUILDING: 'border-sky-300/20 bg-sky-300/10 text-sky-200', READY: 'border-emerald-300/20 bg-emerald-300/10 text-emerald-200', FAILED: 'border-rose-300/20 bg-rose-300/10 text-rose-200' };
const StatusIcon = ({ status }) => ['BUILDING', 'PENDING'].includes(status) ? <Loader size={13} className="animate-spin" /> : status === 'READY' ? <CheckCircle size={13} /> : <AlertCircle size={13} />;

export default function DeploymentPanel({ deployments = [], loading = false, publishing = false, deployingVercel = false, deployingNetlify = false, downloading = false, onPublish, onDeployToVercel, onDeployToNetlify, onDownloadZip, onDeleteDeployment, onConnectCustomDomain, onRemoveCustomDomain, customDomain = null, projectId, deploymentId }) {
  const [deleting, setDeleting] = useState(null);
  const [domain, setDomain] = useState('');
  const [domainError, setDomainError] = useState('');
  const [connectingDomain, setConnectingDomain] = useState(false);
  const dnsVerifiedDomain = customDomain?.status === 'VERIFIED' ? customDomain.domain : '';
  const busy = publishing || deployingVercel || deployingNetlify || loading;
  const formatDate = (date) => new Date(date).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
  const handleDelete = async (id) => { if (deleting) return; setDeleting(id); try { await onDeleteDeployment(id); } finally { setDeleting(null); } };
  const handleConnectDomain = async () => { const normalized = domain.trim().toLowerCase().replace(/^https?:\/\//, '').replace(/\/$/, ''); setDomainError(''); if (!normalized || !/^(?!:\/\/)([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$/.test(normalized)) { setDomainError('Enter a valid domain, for example example.com.'); return; } if (!deploymentId) { setDomainError('Create or publish a deployment before connecting a domain.'); return; } setConnectingDomain(true); try { await onConnectCustomDomain(projectId, deploymentId, normalized); setDomain(''); } finally { setConnectingDomain(false); } };

  return <div className="space-y-5">
    <div className="flex items-end justify-between"><div><p className="eyebrow">Release center</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">Ship your project</h2><p className="mt-2 text-sm text-slate-500">Publish, deploy, and monitor every release from one place.</p></div><span className="hidden rounded-full border border-emerald-300/20 bg-emerald-300/10 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider text-emerald-200 sm:inline">Production ready</span></div>
    <section className="grid gap-3 sm:grid-cols-2">
      <button onClick={onPublish} disabled={publishing || loading} className="group rounded-2xl border border-violet-300/25 bg-violet-500/15 p-4 text-left transition hover:border-violet-200/50 hover:bg-violet-500/20 disabled:opacity-50"><div className="flex items-center justify-between"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-300/15 text-violet-200"><Rocket size={17} /></span><span className="text-xs text-violet-200">{publishing ? 'Publishing...' : 'Publish'}</span></div><p className="mt-5 text-sm font-semibold text-white">Publish Website</p><p className="mt-1 text-xs leading-5 text-slate-400">Create a shareable CraftAI URL from the current files.</p></button>
      <button onClick={onDownloadZip} disabled={downloading || busy} className="group rounded-2xl border border-white/10 bg-white/[0.03] p-4 text-left transition hover:border-cyan-300/30 hover:bg-cyan-300/5 disabled:opacity-50"><div className="flex items-center justify-between"><span className="grid h-9 w-9 place-items-center rounded-xl bg-cyan-300/10 text-cyan-200"><Download size={17} /></span><span className="text-xs text-cyan-200">{downloading ? 'Preparing...' : 'Export'}</span></div><p className="mt-5 text-sm font-semibold text-white">Download ZIP</p><p className="mt-1 text-xs leading-5 text-slate-400">Take the complete project anywhere.</p></button>
    </section>
    <section className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-white">Vercel</p><p className="mt-1 text-xs text-slate-500">Fast edge deployment</p></div><button onClick={onDeployToVercel} disabled={deployingVercel || publishing || loading} className="rounded-lg border border-white/10 px-3 py-2 text-xs font-medium text-slate-200 hover:border-violet-300/30 hover:bg-white/5 disabled:opacity-50">{deployingVercel ? 'Deploying' : 'Deploy'}</button></div></div><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-white">Netlify</p><p className="mt-1 text-xs text-slate-500">Isolated production deploy</p></div><button onClick={onDeployToNetlify} disabled={deployingNetlify || deployingVercel || publishing || loading} className="rounded-lg border border-white/10 px-3 py-2 text-xs font-medium text-slate-200 hover:border-teal-300/30 hover:bg-white/5 disabled:opacity-50">{deployingNetlify ? 'Deploying' : 'Deploy'}</button></div></div></section>
    <section className="rounded-2xl border border-white/10 bg-white/[0.02] p-4"><div className="flex items-center justify-between"><div><p className="section-label">Custom domain</p><p className="mt-1 text-sm font-medium text-white">DNS verification</p></div><Globe2 size={17} className="text-violet-300" /></div>{dnsVerifiedDomain ? <div className="mt-4 rounded-xl border border-emerald-300/20 bg-emerald-300/5 p-3"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold text-emerald-200">DNS verified</p><p className="mt-1 text-sm text-white">{dnsVerifiedDomain}</p><p className="mt-1 text-xs text-slate-500">Hosting and routing are not yet provisioned.</p></div><button onClick={() => onRemoveCustomDomain(projectId, deploymentId)} className="text-xs text-slate-500 hover:text-rose-300">Remove</button></div></div> : <><p className="mt-3 text-xs leading-5 text-slate-500">Verify a CNAME target for this deployment. DNS verification does not activate hosting.</p>{customDomain && <p className="mt-3 rounded-lg border border-amber-300/20 bg-amber-300/5 p-3 text-xs text-amber-200">DNS not verified. {customDomain.instructions?.value && `Point ${customDomain.instructions.name || 'www'} to ${customDomain.instructions.value}.`}</p>}<div className="mt-4 flex gap-2"><input value={domain} onChange={(event) => { setDomain(event.target.value); setDomainError(''); }} onKeyDown={(event) => event.key === 'Enter' && handleConnectDomain()} placeholder="example.com" aria-label="Custom domain" className="focus-ring min-w-0 flex-1 rounded-lg border border-white/10 bg-slate-900 px-3 py-2 text-sm text-white placeholder:text-slate-600" /><button onClick={handleConnectDomain} disabled={connectingDomain} className="rounded-lg bg-violet-500 px-3 py-2 text-xs font-semibold text-white hover:bg-violet-400 disabled:opacity-50">{connectingDomain ? 'Connecting' : 'Connect'}</button></div>{domainError && <p className="mt-2 text-xs text-rose-300">{domainError}</p>}</>}</section>
    <section><div className="mb-3 flex items-center justify-between"><p className="section-label">Deployment history</p><span className="text-xs text-slate-600">{deployments.length} releases</span></div>{loading ? <div className="rounded-xl border border-white/10 bg-white/[0.02] p-8 text-center text-sm text-slate-500">Loading deployment history...</div> : deployments.length === 0 ? <div className="rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">No deployments yet.</div> : <div className="space-y-2">{deployments.map((deployment) => <div key={deployment.id} className="flex items-start justify-between gap-3 rounded-xl border border-white/10 bg-white/[0.03] p-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold text-slate-300">{providers[deployment.provider] || deployment.provider}</span><span className={`inline-flex items-center gap-1 rounded-md border px-2 py-1 text-[10px] font-semibold uppercase tracking-wider ${statusStyles[deployment.status] || ''}`}><StatusIcon status={deployment.status} />{deployment.status}</span></div>{deployment.url && <a href={deployment.url} target="_blank" rel="noopener noreferrer" className="mt-2 flex items-center gap-1 truncate text-xs text-violet-300 hover:underline"><ExternalLink size={12} />{deployment.url}</a>}{deployment.status === 'FAILED' && deployment.errorMessage && <p className="mt-2 text-xs text-rose-300">{deployment.errorMessage}</p>}<p className="mt-2 text-[11px] text-slate-600">{formatDate(deployment.updatedAt || deployment.createdAt)}</p></div><button onClick={() => handleDelete(deployment.id)} disabled={deleting === deployment.id} aria-label="Delete deployment" className="rounded-lg p-2 text-slate-600 hover:bg-rose-400/10 hover:text-rose-300 disabled:opacity-50"><Trash2 size={14} /></button></div>)}</div>}</section>
  </div>;
}
