import { Prisma } from '@prisma/client';
import { z } from 'zod';
import { prisma } from '../config/prisma.js';
import { AppError } from '../utils/appError.js';
import { createStarterFiles } from '../utils/starterFiles.js';
import { limits } from '../config/limits.js';

const pathSchema = z.string().trim().min(1).max(255).refine((path) => !path.startsWith('/') && !path.includes('\\') && !path.split('/').some((part) => !part || part === '.' || part === '..'), 'Use a relative file path without empty or traversal segments.');
const createFileSchema = z.object({ path: pathSchema, content: z.string().max(limits.maxFileBytes).default(''), language: z.string().trim().min(1).max(40).optional() });
const updateFileSchema = z.object({ content: z.string().max(limits.maxFileBytes) });
const fileSelect = { id: true, path: true, content: true, language: true, createdAt: true, updatedAt: true };
const fileListSelect = fileSelect;

function parse(schema, body) { try { return schema.parse(body); } catch (error) { if (error instanceof z.ZodError) throw new AppError(error.issues[0].message, 400); throw error; } }
async function findOwnedProject(projectId, userId) { const project = await prisma.project.findFirst({ where: { id: projectId, userId }, select: { id: true, title: true } }); if (!project) throw new AppError('Project not found.', 404); return project; }
function handleDatabaseError(error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') throw new AppError('A file already exists at this path.', 409); throw error; }

export async function listFiles(request, response, next) { try { await findOwnedProject(request.params.id, request.auth.userId); const files = await prisma.projectFile.findMany({ where: { projectId: request.params.id }, select: fileListSelect, orderBy: { path: 'asc' } }); response.status(200).json({ files }); } catch (error) { next(error); } }
export async function getFile(request, response, next) { try { await findOwnedProject(request.params.id, request.auth.userId); const file = await prisma.projectFile.findFirst({ where: { id: request.params.fileId, projectId: request.params.id }, select: fileSelect }); if (!file) throw new AppError('File not found.', 404); response.status(200).json({ file }); } catch (error) { next(error); } }
export async function createFile(request, response, next) { try { await findOwnedProject(request.params.id, request.auth.userId); const data = parse(createFileSchema, request.body); const existingFiles = await prisma.projectFile.findMany({ where: { projectId: request.params.id }, select: { content: true } }); const totalBytes = existingFiles.reduce((sum, file) => sum + Buffer.byteLength(file.content, 'utf8'), 0); if (existingFiles.length >= limits.maxProjectFiles || totalBytes + Buffer.byteLength(data.content, 'utf8') > limits.maxProjectBytes) throw new AppError('Project file limits exceeded.', 413); const file = await prisma.projectFile.create({ data: { ...data, path: data.path.replace(/\/+/g, '/'), projectId: request.params.id }, select: fileSelect }); response.status(201).json({ file }); } catch (error) { try { handleDatabaseError(error); } catch (databaseError) { next(databaseError); } } }
export async function updateFile(request, response, next) { try { await findOwnedProject(request.params.id, request.auth.userId); const data = parse(updateFileSchema, request.body); const result = await prisma.projectFile.updateMany({ where: { id: request.params.fileId, projectId: request.params.id }, data }); if (!result.count) throw new AppError('File not found.', 404); const file = await prisma.projectFile.findUnique({ where: { id: request.params.fileId }, select: fileSelect }); response.status(200).json({ file }); } catch (error) { next(error); } }
export async function deleteFile(request, response, next) { try { await findOwnedProject(request.params.id, request.auth.userId); const result = await prisma.projectFile.deleteMany({ where: { id: request.params.fileId, projectId: request.params.id } }); if (!result.count) throw new AppError('File not found.', 404); response.status(204).send(); } catch (error) { next(error); } }
export async function initializeFiles(request, response, next) { try { const project = await findOwnedProject(request.params.id, request.auth.userId); const count = await prisma.projectFile.count({ where: { projectId: project.id } }); if (count) throw new AppError('This project already has files.', 409); const result = await prisma.projectFile.createMany({ data: createStarterFiles(project.title).map((file) => ({ ...file, projectId: project.id })) }); const files = await prisma.projectFile.findMany({ where: { projectId: project.id }, select: fileListSelect, orderBy: { path: 'asc' } }); response.status(201).json({ created: result.count, files }); } catch (error) { next(error); } }
